<template>
    <div class="font-mono py-10 mx-auto md:w-6/12">
        <p class="text-3xl text-center">Simulating Competitive Exclusion (Gause's Law)</p>
        <p class="text-xl text-center">Lucas Chang</p>
        <p class="text-lg mt-4 font-semibold text-center">Introduction/Background</p>
        <p class="text-md mt-2 indent-8">Every organism in an ecosystem occupies an ecological niche. An ecological niche is the role and position a species has in its environment. ie. what it eats, what eats it, and how it behaves. Furthermore, two species cannot occupy the same ecological niche. If one species has even a slight reproductive advantage, then it will force the other species to evolve or go extinct in  a process called competitive exclusion (Biology Textbook). The goal of this lab was to demonstrate how competitive exclusion works using a controlled environment. To conduct this lab, I created a computer simulation that models two similar species in a simple environment with a shared food source. By tweaking attributes such as reproduction rate, speed, and energy consumption, this study hopes to demonstrate that even a tiny competitive edge will eliminate another organism occupying an identical niche. I predict that the organism given an edge in any attribute (faster movement, lower barrier to reproduction, etc) will crowd out the other species and become the sole species in the ecosystem.</p>
        <p class="text-lg mt-4 font-semibold text-center">Methodology</p>
        <p class="text-md mt-2 indent-8">In order to create a simulation, I created a stable environment with regularly produced food and two “species”. In the beginning, the two species were identical to one another in all of their attributes except color so that they could be differentiated (in reality, color can play a role in reproductive chance, but I chose to ignore it for the sake of simplicity and visual clarity). Both species have attributes such as reproductive chance, energy consumption, and movement speed that can be tweaked to work with the simulation. I also created counters on the side of the simulation so that you could see the levels of food and the respective populations of both of the species. </p>
	    <p class="text-md mt-2 indent-8">After setting up the visual simulation, I copied the logic into a different program without visuals. This made it faster to process the long simulations. I then tested varying degrees of multipliers for three variables: reproductive chance, energy consumption, and movement speed. I conducted ten trials for each change in the multiplier. For movement speed, I conducted a control and then applied multipliers ranging from 1.1x to 2x. I did the same for the trials with energy consumption. Because reproductive chance wasn’t a multiplier, I simply reduced the chance by 0.1 for each series of trials. I collected all the data in a spreadsheet and calculated averages for each of the ten trials that I used in my results.</p>
        <p class="text-lg mt-4 font-semibold text-center">Results</p>
        <img src="~/assets/images/Speed.png" class="mt-2 mx-auto">
        <p class="text-md italic">Figure 1. This chart shows how much time (in computer ticks) it takes for a species to die out when one species is given a varying speed multiplier. The left side of the graph is the unchanged environment (ie. the control). There is a strong negative correlation.</p>
        <img src="~/assets/images/Energy.png" class="mt-2 mx-auto">
        <p class="text-md italic">Figure 2. This chart shows how much time it takes for a species to die out when one species is given a varying energy consumption multiplier. The left side of the graph is the unchanged environment (ie. the control). There is a strong negative correlation.</p>
        <img src="~/assets/images/Reproduction.png" class="mt-2 mx-auto">
        <p class="text-md italic">Figure 3. This chart shows the time it takes for one species to die out given varying reproduction chances for one of the species. The right side of the graph is the unchanged environment (ie. the control). There is a nominal negative correlation.</p>
        <p class="text-lg mt-4 font-semibold text-center">Discussion</p>
        <p class="text-md mt-2 indent-8">The results from Figures 1 and 2 support my hypothesis that the species given a competitive advantage would become the only species in the environment. In the control for each experiment, it took at least three times longer for one species to get wiped out than if one was given even a slight reproductive advantage. The reason that one species eventually died out even in the control is because there were very few organisms in total so eventually one would die out due to pure chance. In other words, because the two species were identical in the control, it is analogous to one portion of the population dying off, not an actual extinction. However, immediately after one species was given a slight multiplier, we saw a rapid decrease in the time it took for one species to die out. It took 37 times less time for one species to die out when comparing the control with a two-times speed multiplier and 73 times less than when comparing the control with a two-times energy consumption multiplier. While there was conclusive evidence to show a correlation between speed and energy consumption and competitive exclusion, the data for reproductive chance was less conclusive. In fact, when the reproductive chance was lowered for one of the species, it actually took longer for one species to go extinct. However, when using very low rates of reproductive chance for one of the species, the times did reduce marginally.</p>
        <p class="text-md mt-2 indent-8">I created my own experiment to conduct and there was nothing wrong with how it was carried out. However, the way that the environment was constructed had some flaws. I had to simplify the conditions of the environment and it couldn’t accurately reflect an actual ecosystem. Because of this, the relationships between the species may not have been reflected correctly. Furthermore, the reason that the reproductive chance didn’t provide a strong correlation could be because there is no actual analogy for that sort of modification in nature (ie. there is no scenario where just the reproductive “chance” is changed for animals in the wild). This could be fixed by adding more variables to the environment or creating an ecosystem where there are more than two species. This would create a more complex trophic structure that would accurately reflect the real world. </p>
        <p class="text-md mt-2 indent-8">This experiment proved the existence of competitive exclusion even in very simple environments. Learning about competitive exclusion can help explain what certain animals occupy the ecological niches they do despite possessing attributes that don’t reflect how they actually act. </p>
        <p class="text-lg mt-4 font-semibold text-center">Literature Review</p>
        <p class="text-md mt-2 indent-8">The article that I chose examines the difference between black-spotted tokay and red-spotted tokay geckos and how they differ as species. There are very few differences between them, so originally some scientists argued that they should not be considered two different species. However, this study examined the ecological niches of the two species and found that, because they occupy two distinct niches, they are in fact two separate species. Thus, the study acknowledged, ecological niches are an important part of defining what a species is. This connects to my study because it talks about how two species can’t occupy the same niche. Furthermore, it confirms the idea that if two species occupy the same niche (as they do in my control experiments), then they aren’t actually two distinct species.</p>
        <p class="text-lg mt-4 font-semibold text-center">Works Cited</p>
        <p class="text-md mt-2">Zhang, Yueyun, et al. "Insights from Ecological Niche Modeling on the Taxonomic Distinction and Niche Differentiation between the black‐spotted and red‐spotted Tokay Geckoes ( G Ekko Gecko )." Ecology and Evolution, vol. 4, no. 17, 2014, pp. 3383-3394. ProQuest, www.proquest.com/scholarly-journals/insights-ecological-niche-modeling-on-taxonomic/docview/2290724094/se-2, doi:https://doi.org/10.1002/ece3.1183.</p>
        <BackButton />
    </div>
</template>

<style scoped>
* {
    font-family: 'Times New Roman', Times, serif;
}
</style>